name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/upload-release-asset@v1
        with:
          submodules: true
      - run: sudo apt-get install Doxygen -f
      - run: doxygen doxygen.conf
      - run: './html/'
