name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create doxygen
        uses: actions/checkout@v2
      - run: sudo apt-get install doxygen -y
      - run: doxygen doxygen.conf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: './html/'
